[project]
name = "taichi-lab"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fake-bpy-module",
    "mpmath>=1.4.1",
    "scipy>=1.17.1",
    "taichi>=1.7.4",
]

[tool.ruff]
# Only use ruff to format the code, this project does not need linting
ignore = [
    "E402", # module level import not at top of file
    "E722", # do not use bare 'except'
    "F403", # "from module import *" used; unable to detect undefined names
    "F405", # undefined name
    "F811", # redefinition of unused name from line N
    # "F401",  # unused import
    "E731",  # do not assign a lambda expression, use a def
    "E741",  # Ambiguous variable name: `l`
    "F841",  # local variable is assigned to but never used
]

[tool.uv]
index-url = "https://mirrors.aliyun.com/pypi/simple/"
